sonar.projectKey=liam-tasklist-frontend
sonar.projectName=liam-tasklist-frontend
sonar.projectVersion=1.0.0
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=src/__tests__
sonar.test.inclusions=src/__tests__/**/*.test.ts,src/__tests__/**/*.test.tsx

sonar.exclusions=dist/**,node_modules/**,coverage/**,reports/**,.scannerwork/**
sonar.coverage.exclusions=src/__tests__/**,src/main.tsx

sonar.javascript.lcov.reportPaths=coverage/lcov.info
